name: PR Verify Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Check out repository
        uses: actions/checkout@v6

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # Run Python tests
      - name: Run tests
        run: python -m unittest discover -s tests -v