name: 02 CI Workflow

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main

  schedule:
    - cron: "25 10 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
# print python version 
      - name: Show Python version
        run: python --version
# list repo files
      - name: List repo files
        run: ls -la
# shoe date
      - name: Show trigger time
        run: date

      - name: Run tests
        run: python -m unittest discover -s tests -v